
version: 2.0
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

jobs:
  # This job is run on every PR. It must pass for the PR to pass.
  test:
    steps:
      - checkout
      # Run fastlane.
      - run:
          name: test
          command: |
            make test

workflows:
  version: 2
  # This workflow run on every PR and must pass in order for the PR to pass.
  build-and-test:
    jobs:
      - build
